name: keylol action
on: push

jobs:
  gitmand:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Gitmand
        id: gitmand
        uses: yuyinws/gitmand@master

      - name: Update file
        uses: "DamianReeves/write-file-action@master"
        with:
          path: gitmand.svg
          write-mode: overwrite
          contents: ${{ steps.gitmand.outputs.svg }}

      - name: Commit file
        run: |
          git add gitmand.svg
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "update gitmand.svg [skip ci]" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          branch: ${{ github.ref }}
